### ISSUE TITLE
setting camera parameters

### ISSUE THREAD

**Issue by kentaroy47** [ensenso/nxlib-python-interface#1]
Thanks for the great repo! Has been a great help for the project.

Is it possible to set the camera parameter by the saved json file (via Nxview)?

**Comment by kentaroy47** [comment]
Nevermind, I have figured it out.
But it would be nice to have an example since many people use this feature.

**Comment by yguenduez** [comment]
Hello kentaroy,

thanks for using the interface! If you found an answer yourself, it would be helpful, if you write your findings down here, so people with the same question will directly find an answer.

With version 0.3 of this repo you can just set parameters with the lshift operator:
```python
from ensenso_nxlib import NxLibItem

sample_json = '{\"key\": 5}'

item = NxLibItem() # references the root of the tree
item[the][item][you][want_to_set] << sample_json
```

prior versions work with:
```python
item = NxLibItem()
item[the][item][you][want_to_set].set_json(sample_json,True)
```
because there has been a bug apparently.

So im going to close this issue, as it has been answered. If you have any further questions or find bugs, feel free to open new issues.

Best Regards
Yasin

**Comment by kentaroy47** [comment]
@yguenduez 

Thank you for the follow up and the version up!

I got it to work as you mentioned in v0.2:

```python
        import json
        tmp = NxLibItem()
        param = json.dumps(json.load(open("my_json_file.json", "r"))) # load and convert json dict to str
        tmp.set_json(param, True)
        cameras[ITM_PARAMETERS].set_json(tmp[ITM_PARAMETERS].as_json(), True)
```

so i guess in v0.3 it will work with:

```python
param = json.dumps(json.load(open("my_json_file.json", "r")))
cameras[ITM_PARAMETERS] << param
```
