### ISSUE TITLE
NxLibItemTypeNotCompatible error in nx_watch_point_cloud.py

### ISSUE THREAD

**Issue by shoefer** [ensenso/nxlib-python-interface#8]
Hi,

when running the example script ```nx_watch_point_cloud.py``` I get the following error:

```An NxLibException occured: Error Text: NxLibItemTypeNotCompatible```

I identified line 57 to be the problem (https://github.com/ensenso/nxlib-python-interface/blob/master/examples/nx_watch_point_cloud.py#L57)

I resolved the issue by changing this line from
```points = NxLibItem()[ITM_CAMERAS][camera_serial][ITM_IMAGES][ITM_POINT_MAP].get_binary_data()```
to 
```points = NxLibItem()[ITM_CAMERAS][ITM_BY_SERIAL_NO][camera_serial][ITM_IMAGES][ITM_POINT_MAP].get_binary_data()```

Camera model: Ensenso N35-802-16-BL
OS: Ubuntu 16.04.7 LTS
Python: 3.7.9

Thanks,
Sebastian

**Comment by yguenduez** [comment]
Hi Sebastian,

thanks for the hint and the debugging!
When your underlying EnsenoSDK version is smaller than < 2.3.x, then you need that extra piece of path to access the camera item, that is true.
We introduced these breaking path changes in 2.3. But using the old paths will do no harm, if you are using them in versions past 2.3.x, because later versions should be downward compatible. The old paths will link correctly to the new ones.

We wanted to get rid of the old paths, which is why we used the paths introduced in SDK 2.3.x and later and also recommend using these versions.

Best regards,
Yasin

**Comment by shoefer** [comment]
Hi Yasin, 

That make sense, thanks for explaining the issue! I'll update the SDK then to avoid further incompatibilities.

Sebastian

**Comment by yguenduez** [comment]
You are very welcome and have a nice evening!
